### ISSUE TITLE
Hey, may I know the difference between gkiss and kiss?

### ISSUE THREAD

**Issue by Joe23232** [gkisslinux/grepo#17]
Hey, may I know the difference between gkiss and kiss?

**Comment by git-bruh** [comment]
* gkiss uses glibc as the C library instead of musl

* gkiss allows nvidia (proprietary) drivers in repo, kiss allows no proprietary software

* gkiss provides some binaries while official kiss does not (there's a community binary repo though)

Other than this, the repos are the same (only some forked packages to build properly on glinc)﻿

**Comment by Joe23232** [comment]
Ah I see, thanks mate :)
